// MP spelling, first-level areas under each country that act like US states
const SUBDIVISIONS: Record<string, string[]> = {
  canada: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Northwest Territories',
    'Nova Scotia',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Québec',
    'Saskatchewan',
    'Yukon',
    'Yukon Territory',
  ],
  australia: [
    'Australian Capital Territory',
    'New South Wales',
    'Northern Territory',
    'Queensland',
    'South Australia',
    'Tasmania',
    'Victoria',
    'Western Australia',
  ],
  mexico: [
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Coahuila',
    'Colima',
    'Ciudad de México',
    'Mexico City',
    'Durango',
    'Estado de México',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'Michoacán',
    'Morelos',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas',
  ],
  brazil: [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Maranhão',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Pará',
    'Paraíba',
    'Paraná',
    'Pernambuco',
    'Piauí',
    'Rio de Janeiro',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'São Paulo',
    'Sergipe',
    'Tocantins',
  ],
  spain: [
    'Andalucía',
    'Aragón',
    'Asturias',
    'Balearic Islands',
    'Islas Baleares',
    'Basque Country',
    'País Vasco',
    'Canary Islands',
    'Islas Canarias',
    'Cantabria',
    'Castilla-La Mancha',
    'Castilla y León',
    'Catalonia',
    'Cataluña',
    'Catalunya',
    'Extremadura',
    'Galicia',
    'La Rioja',
    'Madrid',
    'Murcia',
    'Navarra',
    'Valencia',
    'Comunidad Valenciana',
  ],
  'united kingdom': ['England', 'Northern Ireland', 'Scotland', 'Wales'],
  'south africa': [
    'Eastern Cape',
    'Free State',
    'Gauteng',
    'KwaZulu-Natal',
    'Limpopo',
    'Mpumalanga',
    'North West',
    'Northern Cape',
    'Western Cape',
  ],
}

const ALIASES: Record<string, string> = { uk: 'united kingdom', 'great britain': 'united kingdom' }

function fold(s: string): string {
  return s.normalize('NFD').replace(/\p{M}/gu, '').trim().toLowerCase()
}

const LOOKUP = new Map(Object.entries(SUBDIVISIONS).map(([country, subs]) => [country, new Set(subs.map(fold))]))

// International paths start at subdivision or country, putting them level with US states
export function normalizeAreaPath(path: string[]): string[] {
  if (path[0] !== 'International' || path.length < 2) return path
  const rest = path.slice(2)
  if (rest.length === 0) return path.slice(1)
  const country = fold(rest[0])
  const subs = LOOKUP.get(ALIASES[country] ?? country)
  if (rest.length > 1 && subs?.has(fold(rest[1]))) return rest.slice(1)
  return rest
}
